[phases.setup]
nixPkgs = ["maven", "jdk17"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[phases.start]
cmd = "cd target && java -jar qr-attendance-system.war"

[start]
cmd = "cd target && java -jar qr-attendance-system.war"
